resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: keycloak-config
    literals:
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_LOG_CONSOLE_COLOR=true
      - KC_LOG_CONSOLE_OUTPUT=default
  - name: keycloak-realms
    files: [files/kokuwa-realm.json]

secretGenerator:
  - name: keycloak-database
    literals:
      - KC_DB_URL_HOST=postgresql
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=password
  - name: keycloak-admin
    literals:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
