apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwt-verifier
spec:
  selector:
    matchLabels:
      app: jwt-verifier
  template:
    metadata:
      labels:
        app: jwt-verifier
    spec:
      containers:
        - image: evolutio/jwt-verifier:latest
          imagePullPolicy: IfNotPresent
          name: jwt-verifier
          ports:
            - containerPort: 80
          env:
            - name: DISCOVERY_URL
              value: http://keycloak.127.0.0.1.nip.io:8080/realms/kokuwa/.well-known/openid-configuration
            - name: CLIENT_ID
              value: angular
            - name: CLIENT_SECRET
              value: changeMe
            - name: LOG_LEVEL
              value: debug
            - name: LOGOUT_QUERY_PARAM
              value: my-fancy-logout-param
            - name: LOGOUT_REDIRECT_URL
              value: "https://google.de"
            - name: PROTECTED_URL_PATH
              value: "/"
            - name: EXTRA_USERINFO_FIELDS
              value: "email,family_name,email_verified"
