micronaut:
  application:
    name: keycloak-angular

  ## see https://docs.micronaut.io/latest/guide/index.html#cors
  server:
    cors:
      enabled: true
      default:
        allowedMethods: [GET]

  ## see https://micronaut-projects.github.io/micronaut-security/latest/guide/#interceptUrlMap
  security:
    intercept-url-map:
      - pattern: /endpoints/**
        access: isAnonymous()

## see https://docs.micronaut.io/latest/guide/index.html#providedEndpoints
endpoints:
  all:
    enabled: false
    port: 8090
    path: /endpoints
    sensitive: false
  health:
    enabled: true
    details-visible: ANONYMOUS
    disk-space:
      enabled: false
    discovery-client:
      enabled: false
